# -------------------------------
# Production Profile (Cloudinary)
# -------------------------------
jobhunter.storage.type=CLOUDINARY

# Hide SQL in production
spring.jpa.show-sql=false

# Cloudinary is used, so UPLOAD_DIR is not needed for storage but kept for reference
