# -------------------------------
# Development Profile (Local)
# -------------------------------
jobhunter.storage.type=CLOUDINARY
#jobhunter.storage.type=LOCAL

# Local storage path (Adjust if needed)
UPLOAD_DIR=file:///home/hieunx/jobhunter_uploads/

# Show SQL for debugging
spring.jpa.show-sql=true

# VNPAY Return URL for Local
vnpay.returnUrl=http://localhost:5173/hr/payment/return

# Frontend URL
jobhunter.frontend.url=http://localhost:5173
